import type { Localized } from './types';

/**
 * Photograph catalogue.
 *
 * The files are generated by `.tools/scripts/fetch-photos.mjs`, and the alt
 * text lives here rather than in that script because it is content: it is
 * translated, it is read aloud to anyone using a screen reader, and it belongs
 * with the other translated strings rather than with the build tooling.
 *
 * All photographs are published under the Unsplash licence. Attribution is not
 * required by that licence but is given anyway — see `public/photos/CREDITS.md`.
 */

export type Photo = {
  slug: string;
  author: string;
  authorUrl: string;
  /** Describes the image for anyone who cannot see it. Never left empty. */
  alt: Localized;
};

export const photos: Record<string, Photo> = {
  'hero-workbench': {
    slug: 'hero-workbench',
    author: 'Nathan Dumlao',
    authorUrl: 'https://unsplash.com/@nate_dumlao',
    alt: {
      pl: 'Otwarta obudowa komputera na blacie warsztatowym, w środku widoczna płyta główna i karta graficzna',
      en: 'An open computer case on a workbench, with the motherboard and graphics card visible inside',
    },
  },
  'motherboard-closeup': {
    slug: 'motherboard-closeup',
    author: 'Umberto',
    authorUrl: 'https://unsplash.com/@umby',
    alt: {
      pl: 'Zbliżenie na płytę główną komputera z widocznymi układami scalonymi i ścieżkami',
      en: 'Close-up of a computer motherboard showing integrated circuits and traces',
    },
  },
  'cpu-in-hand': {
    slug: 'cpu-in-hand',
    author: 'Andrey Matveev',
    authorUrl: 'https://unsplash.com/@amatveev',
    alt: {
      pl: 'Procesor trzymany w dłoni za krawędzie, widoczna pokrywa rozpraszająca ciepło',
      en: 'A processor held by its edges, showing the integrated heat spreader',
    },
  },
  'cooling-fans': {
    slug: 'cooling-fans',
    author: 'Nathan Dumlao',
    authorUrl: 'https://unsplash.com/@nate_dumlao',
    alt: {
      pl: 'Wentylatory chłodzenia zamontowane w obudowie komputera',
      en: 'Cooling fans mounted inside a computer case',
    },
  },
  'gpu-card': {
    slug: 'gpu-card',
    author: 'Nana Dua',
    authorUrl: 'https://unsplash.com/@nanadua11',
    alt: {
      pl: 'Karta graficzna z widocznymi wentylatorami i radiatorem',
      en: 'A graphics card showing its fans and heatsink',
    },
  },
  'memory-modules': {
    slug: 'memory-modules',
    author: 'Harrison Broadbent',
    authorUrl: 'https://unsplash.com/@harrisonbroadbent',
    alt: {
      pl: 'Moduły pamięci RAM z radiatorami, ułożone obok siebie',
      en: 'Memory modules with heat spreaders, laid side by side',
    },
  },
  'cables-tidy': {
    slug: 'cables-tidy',
    author: 'Onur Binay',
    authorUrl: 'https://unsplash.com/@onurbinay',
    alt: {
      pl: 'Wnętrze obudowy komputera z zamontowanym chłodzeniem procesora i kartą graficzną',
      en: 'The inside of a computer case with the CPU cooler and graphics card installed',
    },
  },
  workstation: {
    slug: 'workstation',
    author: 'Christian Wiediger',
    authorUrl: 'https://unsplash.com/@chrisied',
    alt: {
      pl: 'Złożony komputer stacjonarny na biurku obok monitora',
      en: 'A finished desktop computer on a desk beside a monitor',
    },
  },
};

export function getPhoto(slug: string): Photo | undefined {
  return photos[slug];
}
