import type { Case } from './types.ts';

/**
 * Case catalogue.
 *
 * `maxCoolerHeight` and `maxGpuLength` are the two figures that decide whether
 * a build physically goes together, and they are the two most often skipped.
 * Everything else about a case is preference; these two are pass or fail.
 *
 * `volume` is included because it is the honest way to describe "small". A case
 * can be short and deep or tall and narrow, and litres compares them directly
 * where three separate dimensions do not.
 */
export const cases: Case[] = [
  {
    id: 'focus-2',
    category: 'case',
    name: 'Focus 2',
    brand: 'Fractal Design',
    formFactors: ['ATX', 'Micro-ATX', 'Mini-ITX'],
    maxCoolerHeight: 170,
    maxGpuLength: 330,
    radiatorSupport: [240, 280],
    psuFormFactor: 'ATX',
    volume: 45,
    driveBays: 4,
    tier: 'budget',
    price: { min: 250, max: 330 },
    url: 'https://www.fractal-design.com/products/cases/',
    note: {
      pl: 'Dobry przepływ powietrza i sensowne prowadzenie kabli w niskiej cenie. Przy pierwszym składaniu to realna różnica.',
      en: 'Good airflow and sensible cable routing at a low price. On a first build that makes a genuine difference.',
    },
  },
  {
    id: 'north',
    category: 'case',
    name: 'North',
    brand: 'Fractal Design',
    formFactors: ['ATX', 'Micro-ATX', 'Mini-ITX'],
    maxCoolerHeight: 170,
    maxGpuLength: 355,
    radiatorSupport: [240, 280, 360],
    psuFormFactor: 'ATX',
    volume: 47,
    driveBays: 4,
    tier: 'midrange',
    price: { min: 550, max: 700 },
    note: {
      pl: 'Dobry przepływ powietrza w obudowie, która nie wygląda jak sprzęt gamingowy. Front z drewna zamiast szkła i podświetlenia.',
      en: 'Good airflow in a case that does not look like gaming hardware. A wooden front instead of glass and lighting.',
    },
  },
  {
    id: 'define-7',
    category: 'case',
    name: 'Define 7',
    brand: 'Fractal Design',
    formFactors: ['ATX', 'Micro-ATX', 'Mini-ITX'],
    maxCoolerHeight: 185,
    maxGpuLength: 315,
    radiatorSupport: [240, 280, 360, 420],
    psuFormFactor: 'ATX',
    volume: 60,
    driveBays: 14,
    tier: 'high',
    price: { min: 800, max: 1000 },
    note: {
      pl: 'Wyciszona obudowa mieszcząca do czternastu dysków. Najlepszy wybór pod serwer domowy stojący w mieszkaniu.',
      en: 'A sound-dampened case holding up to fourteen drives. The best choice for a home server living in a flat.',
    },
  },
  {
    id: 'terra',
    category: 'case',
    name: 'Terra',
    brand: 'Fractal Design',
    formFactors: ['Mini-ITX'],
    maxCoolerHeight: 77,
    maxGpuLength: 322,
    radiatorSupport: [],
    psuFormFactor: 'SFX',
    volume: 11,
    driveBays: 2,
    tier: 'high',
    price: { min: 750, max: 950 },
    note: {
      pl: 'Poniżej 11 litrów przy zachowaniu miejsca na kartę dwuslotową. Chłodzenie wyłącznie niskoprofilowe — maksymalnie 77 mm.',
      en: 'Under 11 litres while still fitting a two-slot card. Low-profile cooling only — 77 mm maximum.',
    },
  },
  {
    id: 'node-304',
    category: 'case',
    name: 'Node 304',
    brand: 'Fractal Design',
    formFactors: ['Mini-ITX'],
    maxCoolerHeight: 165,
    maxGpuLength: 310,
    radiatorSupport: [240],
    psuFormFactor: 'ATX',
    volume: 19,
    driveBays: 6,
    tier: 'value',
    price: { min: 400, max: 520 },
    note: {
      pl: 'Kompaktowa obudowa mieszcząca sześć dysków i zwykły zasilacz ATX — rzadkie połączenie w tym formacie.',
      en: 'A compact case that holds six drives and a standard ATX supply — a rare combination in this form factor.',
    },
  },
  {
    id: 'lancool-216',
    category: 'case',
    name: 'Lancool 216',
    brand: 'Lian Li',
    formFactors: ['ATX', 'Micro-ATX', 'Mini-ITX'],
    maxCoolerHeight: 180,
    maxGpuLength: 392,
    radiatorSupport: [240, 280, 360],
    psuFormFactor: 'ATX',
    volume: 55,
    driveBays: 4,
    tier: 'midrange',
    price: { min: 480, max: 620 },
    url: 'https://lian-li.com/product-category/pc-cases/',
    note: {
      pl: 'Dwa wentylatory 160 mm z przodu w zestawie. Mieści najdłuższe karty graficzne, łącznie z RTX 5090.',
      en: 'Two 160 mm front fans included. It fits the longest graphics cards, the RTX 5090 among them.',
    },
  },
  {
    id: 'pop-air',
    category: 'case',
    name: 'Pop Air',
    brand: 'Fractal Design',
    formFactors: ['ATX', 'Micro-ATX', 'Mini-ITX'],
    maxCoolerHeight: 170,
    maxGpuLength: 380,
    radiatorSupport: [240, 280, 360],
    psuFormFactor: 'ATX',
    volume: 46,
    driveBays: 4,
    tier: 'budget',
    price: { min: 300, max: 400 },
    note: {
      pl: 'Siatkowy front i miejsce na długie karty w niskiej cenie. Dobra baza dla pierwszego zestawu.',
      en: 'A mesh front and room for long cards at a low price. A good base for a first build.',
    },
  },
  {
    id: 'o11-dynamic-evo',
    category: 'case',
    name: 'O11 Dynamic EVO',
    brand: 'Lian Li',
    formFactors: ['ATX', 'Micro-ATX', 'Mini-ITX'],
    maxCoolerHeight: 167,
    maxGpuLength: 423,
    radiatorSupport: [240, 280, 360],
    psuFormFactor: 'ATX',
    volume: 58,
    driveBays: 4,
    tier: 'high',
    price: { min: 700, max: 900 },
    note: {
      pl: 'Obudowa pokazowa z dwiema szybami. Mieści trzy chłodnice 360 mm, ale front bez wlotów oznacza gorszy przepływ na chłodzeniu powietrznym.',
      en: 'A showcase case with two glass panels. It fits three 360 mm radiators, though a front without intakes means poorer airflow on air cooling.',
    },
  },
  {
    id: 'meshify-2-compact',
    category: 'case',
    name: 'Meshify 2 Compact',
    brand: 'Fractal Design',
    formFactors: ['ATX', 'Micro-ATX', 'Mini-ITX'],
    maxCoolerHeight: 169,
    maxGpuLength: 341,
    radiatorSupport: [240, 280, 360],
    psuFormFactor: 'ATX',
    volume: 39,
    driveBays: 4,
    tier: 'midrange',
    price: { min: 480, max: 620 },
    note: {
      pl: 'Mniejsza obudowa ATX z bardzo dobrym przepływem. Dobry kompromis, gdy pełna wieża jest za duża na biurko.',
      en: 'A smaller ATX case with very good airflow. A good compromise when a full tower is too much for a desk.',
    },
  },
  {
    id: 'ncase-m1',
    category: 'case',
    name: 'M1 V6.1',
    brand: 'NCASE',
    formFactors: ['Mini-ITX'],
    maxCoolerHeight: 130,
    maxGpuLength: 336,
    radiatorSupport: [240],
    psuFormFactor: 'SFX',
    volume: 13,
    driveBays: 2,
    tier: 'flagship',
    price: { min: 1100, max: 1400 },
    note: {
      pl: 'Kultowa obudowa Mini-ITX mieszcząca pełnowymiarową kartę i chłodnicę 240 mm w trzynastu litrach. Montaż wymaga cierpliwości.',
      en: 'A cult Mini-ITX case fitting a full-size card and a 240 mm radiator in thirteen litres. Assembly takes patience.',
    },
  },
];
