import type { Cooler } from './types.ts';

/**
 * Cooler catalogue.
 *
 * `wattage` is the sustained heat this cooler removes while staying reasonably
 * quiet, not an absolute ceiling. That distinction matters: almost any cooler
 * will keep almost any CPU below its thermal limit if you let the fan scream,
 * so a number that ignores noise describes a machine nobody wants to sit next
 * to.
 *
 * `ramClearance` is recorded for air coolers because a large tower overhanging
 * the first memory slot is one of the most common physical conflicts in a
 * build, and it is invisible until the parts are in your hands.
 */
export const coolers: Cooler[] = [
  {
    id: 'assassin-x-120',
    category: 'cooler',
    name: 'Assassin X 120 R SE',
    brand: 'Thermalright',
    kind: 'air',
    sockets: ['am4', 'am5', 'lga1700', 'lga1851'],
    wattage: 130,
    height: 155,
    noise: 28,
    ramClearance: 38,
    tier: 'budget',
    price: { min: 70, max: 110 },
    url: 'https://www.thermalright.com/',
    note: {
      pl: 'Tańsze i cichsze od chłodzenia z zestawu, a montaż zajmuje kilka minut. Do procesorów 65 W w zupełności wystarczy.',
      en: 'Cheaper and quieter than a boxed cooler, and it fits in minutes. Entirely sufficient for 65 W processors.',
    },
  },
  {
    id: 'peerless-assassin-120',
    category: 'cooler',
    name: 'Peerless Assassin 120 SE',
    brand: 'Thermalright',
    kind: 'air',
    sockets: ['am4', 'am5', 'lga1700', 'lga1851'],
    wattage: 220,
    height: 155,
    noise: 31,
    ramClearance: 43,
    tier: 'value',
    price: { min: 140, max: 200 },
    note: {
      pl: 'Podwójna wieża dorównująca chłodnicom 240 mm za ułamek ceny. Najlepszy stosunek wydajności do ceny na rynku.',
      en: 'A dual tower matching 240 mm liquid coolers for a fraction of the price. The best performance per złoty available.',
    },
  },
  {
    id: 'nh-d15-g2',
    category: 'cooler',
    name: 'NH-D15 G2',
    brand: 'Noctua',
    kind: 'air',
    sockets: ['am5', 'lga1700', 'lga1851'],
    wattage: 280,
    height: 168,
    noise: 30,
    ramClearance: 32,
    tier: 'high',
    price: { min: 650, max: 800 },
    url: 'https://noctua.at/en/products/cpu-cooler-retail',
    note: {
      pl: 'Najmocniejsze chłodzenie powietrzne na rynku. Waży 1,5 kg i zasłania pierwszy slot pamięci — sprawdź wysokość modułów.',
      en: 'The strongest air cooler available. It weighs 1.5 kg and overhangs the first memory slot — check your module height.',
    },
  },
  {
    id: 'nh-l12s',
    category: 'cooler',
    name: 'NH-L12S',
    brand: 'Noctua',
    kind: 'air',
    sockets: ['am4', 'am5', 'lga1700', 'lga1851'],
    wattage: 95,
    height: 70,
    noise: 26,
    ramClearance: 48,
    tier: 'midrange',
    price: { min: 300, max: 380 },
    note: {
      pl: 'Niskoprofilowe chłodzenie zaprojektowane pod obudowy, w których wieża się nie mieści. 70 mm wysokości.',
      en: 'A low-profile cooler designed for cases where a tower will not fit. 70 mm tall.',
    },
  },
  {
    id: 'liquid-freezer-iii-240',
    category: 'cooler',
    name: 'Liquid Freezer III 240',
    brand: 'Arctic',
    kind: 'aio',
    sockets: ['am4', 'am5', 'lga1700', 'lga1851'],
    wattage: 250,
    radiatorSize: 240,
    noise: 32,
    tier: 'midrange',
    price: { min: 320, max: 420 },
    url: 'https://www.arctic.de/en/Cooling/CPU-Cooler',
    note: {
      pl: 'Chłodnica 240 mm w rozsądnej cenie. Uwalnia miejsce wokół gniazda procesora i wyrzuca ciepło poza obudowę.',
      en: 'A 240 mm radiator at a sensible price. It frees the space around the socket and exhausts heat outside the case.',
    },
  },
  {
    id: 'liquid-freezer-iii-360',
    category: 'cooler',
    name: 'Liquid Freezer III 360',
    brand: 'Arctic',
    kind: 'aio',
    sockets: ['am4', 'am5', 'lga1700', 'lga1851'],
    wattage: 350,
    radiatorSize: 360,
    noise: 34,
    tier: 'high',
    price: { min: 420, max: 550 },
    note: {
      pl: 'Chłodnica 360 mm utrzymuje taktowania przy godzinach obciążenia wszystkich rdzeni. Wymaga obudowy z miejscem na 360 mm.',
      en: 'A 360 mm radiator holds clocks through hours of all-core load. It needs a case with room for 360 mm.',
    },
  },
  {
    id: 'phantom-spirit-120',
    category: 'cooler',
    name: 'Phantom Spirit 120 SE',
    brand: 'Thermalright',
    kind: 'air',
    sockets: ['am4', 'am5', 'lga1700', 'lga1851'],
    wattage: 245,
    height: 154,
    noise: 30,
    ramClearance: 42,
    tier: 'value',
    price: { min: 160, max: 220 },
    note: {
      pl: 'Siedem ciepłowodów i dwie wieże. Praktycznie dorównuje chłodzeniom trzykrotnie droższym.',
      en: 'Seven heat pipes and two towers. It effectively matches coolers costing three times as much.',
    },
  },
  {
    id: 'nh-u12a',
    category: 'cooler',
    name: 'NH-U12A',
    brand: 'Noctua',
    kind: 'air',
    sockets: ['am5', 'lga1700', 'lga1851'],
    wattage: 200,
    height: 158,
    noise: 27,
    ramClearance: 45,
    tier: 'high',
    price: { min: 480, max: 600 },
    note: {
      pl: 'Pojedyncza wieża o wydajności podwójnej, przy zachowaniu prześwitu nad pamięcią. Wybór, gdy duża wieża nie mieści się nad modułami.',
      en: 'A single tower performing like a dual, while keeping clearance over the memory. The choice when a large tower fouls the modules.',
    },
  },
  {
    id: 'ak620',
    category: 'cooler',
    name: 'AK620 Digital',
    brand: 'DeepCool',
    kind: 'air',
    sockets: ['am4', 'am5', 'lga1700', 'lga1851'],
    wattage: 230,
    height: 160,
    noise: 32,
    ramClearance: 40,
    tier: 'midrange',
    price: { min: 260, max: 340 },
    note: {
      pl: 'Podwójna wieża z wyświetlaczem temperatury. Wyświetlacz to gadżet, ale samo chłodzenie jest solidne.',
      en: 'A dual tower with a temperature display. The display is a gimmick; the cooler underneath is solid.',
    },
  },
  {
    id: 'kraken-360',
    category: 'cooler',
    name: 'Kraken 360 RGB',
    brand: 'NZXT',
    kind: 'aio',
    sockets: ['am4', 'am5', 'lga1700', 'lga1851'],
    wattage: 320,
    radiatorSize: 360,
    noise: 36,
    tier: 'high',
    price: { min: 700, max: 900 },
    note: {
      pl: 'Chłodnica 360 mm z podświetleniem i wyświetlaczem na pompie. Wydajnie, ale drożej niż odpowiedniki bez ozdób.',
      en: 'A 360 mm radiator with lighting and a pump display. Effective, though pricier than equivalents without the decoration.',
    },
  },
  {
    id: 'liquid-freezer-iii-420',
    category: 'cooler',
    name: 'Liquid Freezer III 420',
    brand: 'Arctic',
    kind: 'aio',
    sockets: ['am5', 'lga1700', 'lga1851'],
    wattage: 420,
    radiatorSize: 420,
    noise: 35,
    tier: 'high',
    price: { min: 550, max: 700 },
    note: {
      pl: 'Największa gotowa chłodnica na rynku. Mieści się w niewielu obudowach — sprawdź specyfikację, zanim kupisz.',
      en: 'The largest off-the-shelf radiator available. It fits few cases — check the specification before buying.',
    },
  },
  {
    id: 'stock-wraith',
    category: 'cooler',
    name: 'Wraith Stealth (boxed)',
    brand: 'AMD',
    kind: 'air',
    sockets: ['am4', 'am5'],
    wattage: 70,
    height: 54,
    noise: 38,
    ramClearance: 60,
    tier: 'budget',
    price: { min: 0, max: 60 },
    note: {
      pl: 'Chłodzenie dołączane do części procesorów. Wystarcza do 65 W, ale jest głośne — wymiana na tanią wieżę to jedna z najlepszych inwestycji.',
      en: 'The cooler bundled with some processors. Adequate to 65 W but loud — swapping it for a cheap tower is one of the best-value upgrades there is.',
    },
  },
];
