import type { Cpu } from './types.ts';

/**
 * CPU catalogue.
 *
 * Specifications come from the vendors' published figures. `peakPower` is the
 * boost ceiling rather than the marketing TDP, because that is the number the
 * power supply and the cooler actually have to survive — the two places where
 * trusting the TDP alone leads people wrong.
 *
 * The scores are relative positions on a 0-100 scale, not benchmark results.
 * They exist to drive comparison bars, and treating them as measurements would
 * be a mistake: they say "roughly this much faster", not "exactly this much".
 */
export const cpus: Cpu[] = [
  /* ------------------------------------------------------------ AMD AM5 --- */
  {
    id: 'ryzen-5-7600',
    category: 'cpu',
    name: 'Ryzen 5 7600',
    brand: 'AMD',
    socket: 'am5',
    tier: 'value',
    price: { min: 750, max: 950 },
    cores: 6,
    threads: 12,
    tdp: 65,
    peakPower: 88,
    memory: ['ddr5'],
    integratedGraphics: true,
    gamingScore: 72,
    multiScore: 55,
    unlocked: false,
    url: 'https://www.amd.com/en/products/specifications/processors',
    note: {
      pl: 'Najtańsze sensowne wejście w AM5. Sześć rdzeni w zupełności wystarcza do grania, a niski pobór mocy oznacza, że wystarczy proste chłodzenie.',
      en: 'The cheapest sensible way onto AM5. Six cores are ample for gaming, and the low power draw means a simple cooler is enough.',
    },
  },
  {
    id: 'ryzen-7-7800x3d',
    category: 'cpu',
    name: 'Ryzen 7 7800X3D',
    brand: 'AMD',
    socket: 'am5',
    tier: 'high',
    price: { min: 1500, max: 1800 },
    cores: 8,
    threads: 16,
    tdp: 120,
    peakPower: 162,
    memory: ['ddr5'],
    integratedGraphics: true,
    gamingScore: 96,
    multiScore: 72,
    unlocked: false,
    note: {
      pl: 'Dodatkowa pamięć podręczna 3D V-Cache daje w grach przewagę, której nie widać w testach syntetycznych. Do samego grania trudno o lepszy wybór.',
      en: 'The extra 3D V-Cache gives a gaming lead that synthetic benchmarks do not show. For gaming alone it is hard to beat.',
    },
  },
  {
    id: 'ryzen-7-9700x',
    category: 'cpu',
    name: 'Ryzen 7 9700X',
    brand: 'AMD',
    socket: 'am5',
    tier: 'high',
    price: { min: 1400, max: 1700 },
    cores: 8,
    threads: 16,
    tdp: 65,
    peakPower: 88,
    memory: ['ddr5'],
    integratedGraphics: true,
    gamingScore: 85,
    multiScore: 78,
    unlocked: true,
    note: {
      pl: 'Bardzo niski pobór mocy przy dobrej wydajności — najlepszy wybór do małych obudów, gdzie chłodzenie jest ograniczone wymiarami.',
      en: 'Very low power draw with strong performance — the best choice for small cases where cooling is constrained by dimensions.',
    },
  },
  {
    id: 'ryzen-9-9950x',
    category: 'cpu',
    name: 'Ryzen 9 9950X',
    brand: 'AMD',
    socket: 'am5',
    tier: 'flagship',
    price: { min: 2600, max: 3100 },
    cores: 16,
    threads: 32,
    tdp: 170,
    peakPower: 230,
    memory: ['ddr5'],
    integratedGraphics: true,
    gamingScore: 90,
    multiScore: 100,
    unlocked: true,
    note: {
      pl: 'Szesnaście rdzeni do renderowania i kompilacji. Do samego grania to przepłacanie — w grach 7800X3D bywa szybszy.',
      en: 'Sixteen cores for rendering and compiling. For gaming alone it is overpaying — the 7800X3D is often faster there.',
    },
  },
  {
    id: 'ryzen-7-8700g',
    category: 'cpu',
    name: 'Ryzen 7 8700G',
    brand: 'AMD',
    socket: 'am5',
    tier: 'midrange',
    price: { min: 1150, max: 1400 },
    cores: 8,
    threads: 16,
    tdp: 65,
    peakPower: 88,
    memory: ['ddr5'],
    integratedGraphics: true,
    gamingScore: 62,
    multiScore: 68,
    unlocked: true,
    note: {
      pl: 'Najmocniejsza grafika zintegrowana na desktopie. Pozwala grać w 1080p i odtwarzać 4K bez osobnej karty graficznej.',
      en: 'The strongest integrated graphics on desktop. It games at 1080p and plays 4K with no discrete card at all.',
    },
  },
  /* ------------------------------------------------------------ AMD AM4 --- */
  {
    id: 'ryzen-5-5600',
    category: 'cpu',
    name: 'Ryzen 5 5600',
    brand: 'AMD',
    socket: 'am4',
    tier: 'budget',
    price: { min: 420, max: 560 },
    cores: 6,
    threads: 12,
    tdp: 65,
    peakPower: 76,
    memory: ['ddr4'],
    integratedGraphics: false,
    gamingScore: 58,
    multiScore: 46,
    unlocked: true,
    note: {
      pl: 'Najlepszy stosunek ceny do wydajności na AM4 i wciąż w zupełności wystarczający do grania w 1080p.',
      en: 'The best price-to-performance option on AM4, and still entirely sufficient for 1080p gaming.',
    },
  },
  {
    id: 'ryzen-7-5800x3d',
    category: 'cpu',
    name: 'Ryzen 7 5800X3D',
    brand: 'AMD',
    socket: 'am4',
    tier: 'midrange',
    price: { min: 1000, max: 1300 },
    cores: 8,
    threads: 16,
    tdp: 105,
    peakPower: 142,
    memory: ['ddr4'],
    integratedGraphics: false,
    gamingScore: 82,
    multiScore: 62,
    unlocked: false,
    note: {
      pl: 'Ostatnia i najmocniejsza modernizacja dla AM4. Sensowna, jeśli masz już płytę i pamięć DDR4 — nie warto kupować platformy od zera.',
      en: 'The last and strongest upgrade for AM4. Worth it if you already own the board and DDR4 — not worth buying the platform from scratch.',
    },
  },
  /* -------------------------------------------------------- Intel 1851 --- */
  {
    id: 'core-ultra-5-245k',
    category: 'cpu',
    name: 'Core Ultra 5 245K',
    brand: 'Intel',
    socket: 'lga1851',
    tier: 'midrange',
    price: { min: 1150, max: 1400 },
    cores: 14,
    threads: 14,
    tdp: 125,
    peakPower: 159,
    memory: ['ddr5'],
    integratedGraphics: true,
    gamingScore: 78,
    multiScore: 74,
    unlocked: true,
    url: 'https://ark.intel.com/',
    note: {
      pl: 'Rozsądny średniak Intela z wbudowanym NPU. Dobra wydajność wielowątkowa przy niskim poborze mocy w spoczynku.',
      en: "Intel's sensible mid-range option with an on-package NPU. Good multi-threaded performance and low idle power.",
    },
  },
  {
    id: 'core-ultra-7-265k',
    category: 'cpu',
    name: 'Core Ultra 7 265K',
    brand: 'Intel',
    socket: 'lga1851',
    tier: 'high',
    price: { min: 1600, max: 1950 },
    cores: 20,
    threads: 20,
    tdp: 125,
    peakPower: 250,
    memory: ['ddr5'],
    integratedGraphics: true,
    gamingScore: 86,
    multiScore: 90,
    unlocked: true,
    note: {
      pl: 'Dużo rdzeni do montażu wideo i kompilacji. Pod pełnym obciążeniem potrafi pobrać 250 W, więc wymaga mocnego chłodzenia.',
      en: 'Plenty of cores for video editing and compiling. It can draw 250 W under full load, so it needs serious cooling.',
    },
  },
  /* -------------------------------------------------------- Intel 1700 --- */
  {
    id: 'core-i5-14400f',
    category: 'cpu',
    name: 'Core i5-14400F',
    brand: 'Intel',
    socket: 'lga1700',
    tier: 'budget',
    price: { min: 620, max: 800 },
    cores: 10,
    threads: 16,
    tdp: 65,
    peakPower: 148,
    memory: ['ddr4', 'ddr5'],
    integratedGraphics: false,
    gamingScore: 68,
    multiScore: 58,
    unlocked: false,
    note: {
      pl: 'Tani wybór na dojrzałej platformie. Wersja F nie ma grafiki zintegrowanej, więc karta graficzna jest tu obowiązkowa.',
      en: 'A cheap option on a mature platform. The F suffix means no integrated graphics, so a discrete card is mandatory.',
    },
  },
  {
    id: 'core-i5-14600k',
    category: 'cpu',
    name: 'Core i5-14600K',
    brand: 'Intel',
    socket: 'lga1700',
    tier: 'value',
    price: { min: 1050, max: 1300 },
    cores: 14,
    threads: 20,
    tdp: 125,
    peakPower: 181,
    memory: ['ddr4', 'ddr5'],
    integratedGraphics: true,
    gamingScore: 80,
    multiScore: 76,
    unlocked: true,
    note: {
      pl: 'Mocny średniak z możliwością podkręcania. Dobra opcja, jeśli masz już pamięć DDR4 i chcesz ją zachować.',
      en: 'A strong mid-range chip with overclocking. A good option if you already own DDR4 and want to keep it.',
    },
  },
];
