import type { Gpu } from './types.ts';

/**
 * Graphics card catalogue.
 *
 * `recommendedPsu` is the manufacturer's own figure rather than something
 * derived from board power. That is deliberate: modern cards draw brief
 * transient spikes well above their rated wattage, and the vendor number
 * already accounts for them where a simple sum would not.
 *
 * `length` and `slots` exist because they are the two specifications that
 * actually stop a build — a card that does not physically fit the case is a
 * problem no amount of performance makes up for.
 */
export const gpus: Gpu[] = [
  {
    id: 'rtx-5090',
    category: 'gpu',
    name: 'GeForce RTX 5090',
    brand: 'NVIDIA',
    tier: 'flagship',
    price: { min: 9500, max: 13000 },
    vram: 32,
    tdp: 575,
    recommendedPsu: 1000,
    length: 336,
    slots: 3,
    performanceScore: 100,
    targetResolution: '4K',
    url: 'https://www.nvidia.com/en-eu/geforce/graphics-cards/',
    note: {
      pl: 'Najszybsza karta na rynku i jedyna sensowna do 4K przy 120 klatkach z ray tracingiem. Wymaga zasilacza 1000 W i obudowy, w której się zmieści.',
      en: 'The fastest card available and the only sensible choice for 4K at 120 frames with ray tracing. It needs a 1000 W supply and a case it actually fits.',
    },
  },
  {
    id: 'rtx-5080',
    category: 'gpu',
    name: 'GeForce RTX 5080',
    brand: 'NVIDIA',
    tier: 'flagship',
    price: { min: 5200, max: 6800 },
    vram: 16,
    tdp: 360,
    recommendedPsu: 850,
    length: 304,
    slots: 3,
    performanceScore: 82,
    targetResolution: '4K',
    note: {
      pl: 'Karta pod 4K bez ekstremalnych ustawień. 16 GB pamięci wystarcza dziś wszędzie, ale przy najnowszych tytułach z ray tracingiem bywa ciasno.',
      en: 'Sized for 4K short of extreme settings. Its 16 GB is enough everywhere today, though the newest ray-traced titles can push against it.',
    },
  },
  {
    id: 'rtx-5070-ti',
    category: 'gpu',
    name: 'GeForce RTX 5070 Ti',
    brand: 'NVIDIA',
    tier: 'high',
    price: { min: 3600, max: 4500 },
    vram: 16,
    tdp: 300,
    recommendedPsu: 750,
    length: 300,
    slots: 3,
    performanceScore: 70,
    targetResolution: '1440p',
    note: {
      pl: 'Najrozsądniejszy punkt dla 1440p przy wysokim odświeżaniu. 16 GB pamięci daje zapas na kolejne lata i na render 3D.',
      en: 'The most sensible point for high-refresh 1440p. Its 16 GB leaves headroom for the coming years and for 3D rendering.',
    },
  },
  {
    id: 'rtx-5070',
    category: 'gpu',
    name: 'GeForce RTX 5070',
    brand: 'NVIDIA',
    tier: 'midrange',
    price: { min: 2500, max: 3200 },
    vram: 12,
    tdp: 250,
    recommendedPsu: 650,
    length: 242,
    slots: 2,
    performanceScore: 58,
    targetResolution: '1440p',
    note: {
      pl: 'Dobra karta do 1440p z zapasem na skalowanie obrazu. Dwa sloty i krótsza płytka ułatwiają montaż w mniejszych obudowach.',
      en: 'A good 1440p card with headroom for upscaling. Two slots and a shorter board make it easier to fit in smaller cases.',
    },
  },
  {
    id: 'rx-9070-xt',
    category: 'gpu',
    name: 'Radeon RX 9070 XT',
    brand: 'AMD',
    tier: 'high',
    price: { min: 2900, max: 3700 },
    vram: 16,
    tdp: 304,
    recommendedPsu: 750,
    length: 287,
    slots: 3,
    performanceScore: 66,
    targetResolution: '1440p',
    url: 'https://www.amd.com/en/products/graphics/desktops/radeon.html',
    note: {
      pl: 'Mocna alternatywa dla 5070 Ti, zwykle tańsza przy podobnej wydajności w rasteryzacji. Słabsza w ray tracingu.',
      en: 'A strong alternative to the 5070 Ti, usually cheaper for similar rasterisation performance. Weaker in ray tracing.',
    },
  },
  {
    id: 'rtx-5060-ti',
    category: 'gpu',
    name: 'GeForce RTX 5060 Ti 16GB',
    brand: 'NVIDIA',
    tier: 'value',
    price: { min: 1750, max: 2200 },
    vram: 16,
    tdp: 180,
    recommendedPsu: 600,
    length: 242,
    slots: 2,
    performanceScore: 44,
    targetResolution: '1440p',
    note: {
      pl: 'Wersja 16 GB jest wyraźnie lepszym wyborem niż 8 GB — różnica w cenie zwraca się w nowszych grach, które przekraczają 8 GB.',
      en: 'The 16 GB version is clearly the better buy over the 8 GB — the price difference pays off in newer games that exceed 8 GB.',
    },
  },
  {
    id: 'rx-9060-xt',
    category: 'gpu',
    name: 'Radeon RX 9060 XT 16GB',
    brand: 'AMD',
    tier: 'value',
    price: { min: 1550, max: 2000 },
    vram: 16,
    tdp: 160,
    recommendedPsu: 550,
    length: 250,
    slots: 2,
    performanceScore: 41,
    targetResolution: '1080p',
    note: {
      pl: 'Dobry stosunek pamięci do ceny. 16 GB w tej półce to rzadkość i realna przewaga w nowszych tytułach.',
      en: 'A good memory-to-price ratio. 16 GB at this tier is rare and a genuine advantage in newer titles.',
    },
  },
  {
    id: 'rtx-5060',
    category: 'gpu',
    name: 'GeForce RTX 5060',
    brand: 'NVIDIA',
    tier: 'budget',
    price: { min: 1250, max: 1600 },
    vram: 8,
    tdp: 145,
    recommendedPsu: 550,
    length: 200,
    slots: 2,
    performanceScore: 34,
    targetResolution: '1080p',
    note: {
      pl: 'Sensowna do 1080p, ale 8 GB pamięci to dziś minimum i w części nowych gier trzeba będzie zejść z ustawieniami tekstur.',
      en: 'Sensible for 1080p, but 8 GB is the bare minimum today and some new games will need their texture settings lowered.',
    },
  },
  {
    id: 'rx-7600',
    category: 'gpu',
    name: 'Radeon RX 7600',
    brand: 'AMD',
    tier: 'budget',
    price: { min: 1000, max: 1350 },
    vram: 8,
    tdp: 165,
    recommendedPsu: 550,
    length: 204,
    slots: 2,
    performanceScore: 28,
    targetResolution: '1080p',
    note: {
      pl: 'Najtańsze rozsądne wejście w granie w 1080p. Do wyższych rozdzielczości zdecydowanie za słaba.',
      en: 'The cheapest reasonable entry into 1080p gaming. Decidedly not enough for higher resolutions.',
    },
  },
  {
    id: 'rtx-5070-ti-super',
    category: 'gpu',
    name: 'GeForce RTX 5070 Ti SUPER',
    brand: 'NVIDIA',
    tier: 'high',
    price: { min: 4200, max: 5100 },
    vram: 24,
    tdp: 350,
    recommendedPsu: 850,
    length: 310,
    slots: 3,
    performanceScore: 76,
    targetResolution: '4K',
    note: {
      pl: '24 GB pamięci przy wydajności bliskiej 5080. Sensowna dla renderowania i pracy z modelami AI, gdzie pamięć jest twardym ograniczeniem.',
      en: '24 GB of memory at performance close to the 5080. Sensible for rendering and AI work, where memory is a hard limit.',
    },
  },
  {
    id: 'rx-9070',
    category: 'gpu',
    name: 'Radeon RX 9070',
    brand: 'AMD',
    tier: 'midrange',
    price: { min: 2300, max: 2900 },
    vram: 16,
    tdp: 220,
    recommendedPsu: 650,
    length: 270,
    slots: 2,
    performanceScore: 56,
    targetResolution: '1440p',
    note: {
      pl: '16 GB w średniej półce i niski pobór mocy. Dobra propozycja do 1440p, jeśli ray tracing nie jest priorytetem.',
      en: '16 GB in the mid-range at low power draw. A good 1440p proposition if ray tracing is not a priority.',
    },
  },
  {
    id: 'rtx-5080-super',
    category: 'gpu',
    name: 'GeForce RTX 5080 SUPER',
    brand: 'NVIDIA',
    tier: 'flagship',
    price: { min: 6000, max: 7600 },
    vram: 24,
    tdp: 400,
    recommendedPsu: 950,
    length: 320,
    slots: 3,
    performanceScore: 88,
    targetResolution: '4K',
    note: {
      pl: 'Karta do 4K z zapasem pamięci. Różnica względem 5090 jest wyraźnie mniejsza niż różnica w cenie.',
      en: 'A 4K card with memory headroom. The gap to the 5090 is markedly smaller than the gap in price.',
    },
  },
  {
    id: 'rtx-5050',
    category: 'gpu',
    name: 'GeForce RTX 5050',
    brand: 'NVIDIA',
    tier: 'budget',
    price: { min: 900, max: 1200 },
    vram: 8,
    tdp: 130,
    recommendedPsu: 500,
    length: 200,
    slots: 2,
    performanceScore: 26,
    targetResolution: '1080p',
    note: {
      pl: 'Najtańsza karta z aktualnej generacji. Do e-sportu w 1080p w porządku, do nowych tytułów AAA już z trudem.',
      en: 'The cheapest card of the current generation. Fine for esports at 1080p, a struggle for new AAA titles.',
    },
  },
  {
    id: 'arc-b580',
    category: 'gpu',
    name: 'Arc B580',
    brand: 'Intel',
    tier: 'budget',
    price: { min: 1050, max: 1400 },
    vram: 12,
    tdp: 190,
    recommendedPsu: 600,
    length: 272,
    slots: 2,
    performanceScore: 32,
    targetResolution: '1080p',
    url: 'https://www.intel.com/content/www/us/en/products/details/discrete-gpus/arc.html',
    note: {
      pl: '12 GB pamięci w budżetowej półce, co jest tu rzadkością. Sterowniki wyraźnie dojrzały, ale w starszych tytułach wciąż bywają nierówne.',
      en: '12 GB of memory at a budget price, which is rare here. The drivers have matured considerably, though older titles can still be uneven.',
    },
  },
];
