import type { Psu } from './types.ts';

/**
 * Power supply catalogue.
 *
 * `warranty` is listed alongside the efficiency rating because it is the more
 * honest signal of the two. An 80 Plus badge describes efficiency and nothing
 * else — an unbranded unit can carry one and still be a poor choice — whereas
 * a manufacturer only offers ten years on a design they expect to survive it.
 *
 * `atx31` matters for a specific, current failure: modern graphics cards draw
 * brief spikes far above their rated power, and an older supply's protection
 * circuits read those as a fault and shut the machine down mid-game.
 */
export const psus: Psu[] = [
  {
    id: 'system-power-10-550',
    category: 'psu',
    name: 'System Power 10 550 W',
    brand: 'be quiet!',
    wattage: 550,
    efficiency: 'Bronze',
    modular: 'no',
    formFactor: 'ATX',
    atx31: true,
    warranty: 3,
    tier: 'budget',
    price: { min: 220, max: 300 },
    url: 'https://www.bequiet.com/en/powersupply',
    note: {
      pl: 'Najtańszy zasilacz, który można polecić bez zastrzeżeń. Kable nieodłączane, więc nadmiar trzeba gdzieś schować.',
      en: 'The cheapest supply that can be recommended without caveats. Non-modular, so the excess cable has to go somewhere.',
    },
  },
  {
    id: 'pure-power-12m-650',
    category: 'psu',
    name: 'Pure Power 12 M 650 W',
    brand: 'be quiet!',
    wattage: 650,
    efficiency: 'Gold',
    modular: 'full',
    formFactor: 'ATX',
    atx31: true,
    warranty: 10,
    tier: 'value',
    price: { min: 380, max: 480 },
    note: {
      pl: 'Dziesięcioletnia gwarancja i pełna modularność. Rozsądny wybór do zestawu ze średnią kartą graficzną.',
      en: 'A ten-year warranty and full modularity. A sensible choice for a build with a mid-range graphics card.',
    },
  },
  {
    id: 'pure-power-12m-750',
    category: 'psu',
    name: 'Pure Power 12 M 750 W',
    brand: 'be quiet!',
    wattage: 750,
    efficiency: 'Gold',
    modular: 'full',
    formFactor: 'ATX',
    atx31: true,
    warranty: 10,
    tier: 'midrange',
    price: { min: 450, max: 570 },
    note: {
      pl: '750 W z zapasem na skoki poboru współczesnych kart. Najczęściej wybierana moc do zestawów do 1440p.',
      en: '750 W with headroom for the transient spikes modern cards produce. The most commonly chosen wattage for 1440p builds.',
    },
  },
  {
    id: 'focus-gx-850',
    category: 'psu',
    name: 'Focus GX-850',
    brand: 'Seasonic',
    wattage: 850,
    efficiency: 'Gold',
    modular: 'full',
    formFactor: 'ATX',
    atx31: true,
    warranty: 10,
    tier: 'high',
    price: { min: 620, max: 780 },
    url: 'https://seasonic.com/wattage-calculator/',
    note: {
      pl: 'Bardzo dobra jednostka do mocnych zestawów. 850 W daje zapas przy jednoczesnym obciążeniu procesora i karty.',
      en: 'A very good unit for powerful builds. 850 W leaves headroom with the CPU and GPU both loaded.',
    },
  },
  {
    id: 'prime-tx-1000',
    category: 'psu',
    name: 'PRIME TX-1000',
    brand: 'Seasonic',
    wattage: 1000,
    efficiency: 'Titanium',
    modular: 'full',
    formFactor: 'ATX',
    atx31: true,
    warranty: 12,
    tier: 'flagship',
    price: { min: 1400, max: 1800 },
    note: {
      pl: 'Konieczny przy RTX 5090. Sprawność Titanium i dwunastoletnia gwarancja, ale cena odpowiada jakości.',
      en: 'Required for an RTX 5090. Titanium efficiency and a twelve-year warranty, though the price matches the quality.',
    },
  },
  {
    id: 'sf750',
    category: 'psu',
    name: 'SF750 SFX',
    brand: 'Corsair',
    wattage: 750,
    efficiency: 'Platinum',
    modular: 'full',
    formFactor: 'SFX',
    atx31: true,
    warranty: 7,
    tier: 'high',
    price: { min: 850, max: 1050 },
    note: {
      pl: 'Format SFX do obudów Mini-ITX. Zasilacze SFX są droższe od ATX o tej samej mocy — to koszt małych wymiarów.',
      en: 'The SFX form factor for Mini-ITX cases. SFX units cost more than ATX of the same wattage — that is the price of small.',
    },
  },
  {
    id: 'rm850x',
    category: 'psu',
    name: 'RM850x (2024)',
    brand: 'Corsair',
    wattage: 850,
    efficiency: 'Gold',
    modular: 'full',
    formFactor: 'ATX',
    atx31: true,
    warranty: 10,
    tier: 'high',
    price: { min: 580, max: 730 },
    note: {
      pl: 'Cicha jednostka z wentylatorem zatrzymującym się przy niskim obciążeniu. Popularny wybór do zestawów z mocną kartą.',
      en: 'A quiet unit whose fan stops at low load. A popular choice for builds with a powerful card.',
    },
  },
  {
    id: 'mpg-a1000g',
    category: 'psu',
    name: 'MPG A1000G PCIE5',
    brand: 'MSI',
    wattage: 1000,
    efficiency: 'Gold',
    modular: 'full',
    formFactor: 'ATX',
    atx31: true,
    warranty: 10,
    tier: 'high',
    price: { min: 780, max: 980 },
    note: {
      pl: 'Tysiąc watów ze złączem 12V-2x6 w zestawie. Sensowna podstawa pod najmocniejsze karty bez przepłacania za Titanium.',
      en: 'A thousand watts with a 12V-2x6 connector included. A sensible base for the fastest cards without paying for Titanium.',
    },
  },
  {
    id: 'sf850l',
    category: 'psu',
    name: 'SF850L SFX-L',
    brand: 'Corsair',
    wattage: 850,
    efficiency: 'Gold',
    modular: 'full',
    formFactor: 'SFX',
    atx31: true,
    warranty: 10,
    tier: 'flagship',
    price: { min: 1000, max: 1250 },
    note: {
      pl: 'Format SFX-L jest nieco dłuższy od zwykłego SFX, więc mieści cichszy wentylator. Sprawdź, czy obudowa go przyjmie.',
      en: 'The SFX-L form factor is slightly longer than plain SFX, which makes room for a quieter fan. Check the case accepts it.',
    },
  },
  {
    id: 'system-power-11-750',
    category: 'psu',
    name: 'System Power 11 750 W',
    brand: 'be quiet!',
    wattage: 750,
    efficiency: 'Bronze',
    modular: 'no',
    formFactor: 'ATX',
    atx31: true,
    warranty: 3,
    tier: 'budget',
    price: { min: 300, max: 390 },
    note: {
      pl: 'Tania jednostka o rozsądnej mocy. Kable nieodłączane i tylko trzyletnia gwarancja — to widać w cenie.',
      en: 'An inexpensive unit at a sensible wattage. Non-modular with a three-year warranty — and the price reflects it.',
    },
  },
];
