/**
 * Downloads the stock photography and generates responsive AVIF/WebP variants.
 *
 *   node .tools/scripts/fetch-photos.mjs
 *
 * Every photograph here is published under the Unsplash licence, which permits
 * commercial and non-commercial use without permission. Attribution is not
 * legally required under that licence, but it is recorded in CREDITS.md and
 * shown on the site anyway: crediting the photographer is the decent thing to
 * do, and it also documents where each file came from if the licence is ever
 * questioned.
 *
 * The generated files are committed, so a normal build never runs this script.
 * Re-run it only when adding or replacing a photograph.
 */

import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const outputDir = join(here, '..', '..', 'public', 'photos');

/**
 * The photograph set.
 *
 * `id` is the Unsplash photo id, which is what makes each entry verifiable:
 * anyone can open unsplash.com/photos/<id> and confirm the licence and the
 * photographer for themselves.
 */
const photos = [
  {
    slug: 'hero-workbench',
    id: 'photo-1587202372775-e229f172b9d7',
    author: 'Nathan Dumlao',
    authorUrl: 'https://unsplash.com/@nate_dumlao',
    alt: {
      pl: 'Otwarta obudowa komputera na blacie warsztatowym, w środku widoczna płyta główna i karta graficzna',
      en: 'An open computer case on a workbench, with the motherboard and graphics card visible inside',
    },
  },
  {
    slug: 'motherboard-closeup',
    id: 'photo-1518770660439-4636190af475',
    author: 'Umberto',
    authorUrl: 'https://unsplash.com/@umby',
    alt: {
      pl: 'Zbliżenie na płytę główną komputera z widocznymi układami scalonymi i ścieżkami',
      en: 'Close-up of a computer motherboard showing integrated circuits and traces',
    },
  },
  {
    slug: 'cpu-in-hand',
    id: 'photo-1555617981-dac3880eac6e',
    author: 'Andrey Matveev',
    authorUrl: 'https://unsplash.com/@amatveev',
    alt: {
      pl: 'Procesor trzymany w dłoni za krawędzie, widoczna pokrywa rozpraszająca ciepło',
      en: 'A processor held by its edges, showing the integrated heat spreader',
    },
  },
  {
    slug: 'cooling-fans',
    id: 'photo-1587202372616-b43abea06c2a',
    author: 'Nathan Dumlao',
    authorUrl: 'https://unsplash.com/@nate_dumlao',
    alt: {
      pl: 'Wentylatory chłodzenia zamontowane w obudowie komputera',
      en: 'Cooling fans mounted inside a computer case',
    },
  },
  {
    slug: 'gpu-card',
    id: 'photo-1591488320449-011701bb6704',
    author: 'Nana Dua',
    authorUrl: 'https://unsplash.com/@nanadua11',
    alt: {
      pl: 'Karta graficzna z widocznymi wentylatorami i radiatorem',
      en: 'A graphics card showing its fans and heatsink',
    },
  },
  {
    slug: 'memory-modules',
    id: 'photo-1541029071515-84cc54f84dc5',
    author: 'Harrison Broadbent',
    authorUrl: 'https://unsplash.com/@harrisonbroadbent',
    alt: {
      pl: 'Moduły pamięci RAM z radiatorami, ułożone obok siebie',
      en: 'Memory modules with heat spreaders, laid side by side',
    },
  },
  {
    slug: 'cables-tidy',
    id: 'photo-1624705002806-5d72df19c3ad',
    author: 'Onur Binay',
    authorUrl: 'https://unsplash.com/@onurbinay',
    alt: {
      pl: 'Wnętrze obudowy komputera z zamontowanym chłodzeniem procesora i kartą graficzną',
      en: 'The inside of a computer case with the CPU cooler and graphics card installed',
    },
  },
  {
    slug: 'workstation',
    id: 'photo-1593640408182-31c70c8268f5',
    author: 'Christian Wiediger',
    authorUrl: 'https://unsplash.com/@chrisied',
    alt: {
      pl: 'Złożony komputer stacjonarny na biurku obok monitora',
      en: 'A finished desktop computer on a desk beside a monitor',
    },
  },
];

/* Widths generated for each photograph. The set covers a card thumbnail, a
   half-width section image and a full-bleed hero on a high-density display. */
const WIDTHS = [400, 800, 1200, 1600];

async function main() {
  const { default: sharp } = await import('sharp');

  await mkdir(outputDir, { recursive: true });

  const credits = [
    '# Photo credits',
    '',
    'All photographs are published under the [Unsplash Licence](https://unsplash.com/license),',
    'which permits use without permission. Attribution is not required by that',
    'licence; it is given here and on the site because crediting the',
    'photographer is right, and because it documents the provenance of each file.',
    '',
    'Generated by `.tools/scripts/fetch-photos.mjs` — do not edit by hand.',
    '',
    '| File | Photographer | Source |',
    '| --- | --- | --- |',
  ];

  for (const photo of photos) {
    /* `q=85` is the point where further quality gains stop being visible while
       the file keeps growing; `fm=jpg` gets a clean source to re-encode from. */
    const source = `https://images.unsplash.com/${photo.id}?w=2000&q=85&fm=jpg&fit=max`;

    process.stdout.write(`${photo.slug}: downloading… `);
    const response = await fetch(source);
    if (!response.ok) {
      console.error(`FAILED (HTTP ${response.status})`);
      process.exitCode = 1;
      continue;
    }

    const buffer = Buffer.from(await response.arrayBuffer());

    for (const width of WIDTHS) {
      /* AVIF first: it is roughly half the size of WebP at matching quality,
         and every browser that cannot read it falls back to the WebP below. */
      await sharp(buffer)
        .resize(width, null, { withoutEnlargement: true })
        .avif({ quality: 62 })
        .toFile(join(outputDir, `${photo.slug}-${width}.avif`));

      await sharp(buffer)
        .resize(width, null, { withoutEnlargement: true })
        .webp({ quality: 78 })
        .toFile(join(outputDir, `${photo.slug}-${width}.webp`));
    }

    /* A tiny blurred placeholder, inlined as a data URI. It occupies the space
       while the real image loads, so the layout does not jump and the reader
       sees the shape of the picture rather than an empty rectangle. */
    const placeholder = await sharp(buffer)
      .resize(16, null)
      .blur(1.2)
      .webp({ quality: 30 })
      .toBuffer();

    await writeFile(
      join(outputDir, `${photo.slug}.blur.txt`),
      `data:image/webp;base64,${placeholder.toString('base64')}`,
      'utf8',
    );

    credits.push(
      `| \`${photo.slug}\` | ${photo.author} | [unsplash.com/photos/${photo.id}](https://unsplash.com/photos/${photo.id}) |`,
    );

    console.log('done');
  }

  await writeFile(join(outputDir, 'CREDITS.md'), credits.join('\n') + '\n', 'utf8');
  console.log(`\nWrote ${photos.length} photographs to public/photos/.`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
